---
title: "CorrigeDatacamp"
output: html_document
date: "2026-04-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readxl)
library(openxlsx)
library(stringr)
```

```{r}
# 1. Descomprimir el fichero
zip_file <- "2025-26 Tractament de les dades Gr.A-T (36423)-Tarea Intermediate R(Datacamp)-3281647 (1).zip" # Ajustar al nombre real
unzip(zip_file, exdir = "entregas_descomprimidas")
```


```{r}
# 2. Localización de archivos con Regex
# Buscamos puntos.txt (o variaciones) y certificados pdf
all_files <- list.files("entregas_descomprimidas", recursive = TRUE, full.names = TRUE)

# Regex: que contenga "puntos" y termine en .txt
puntos_files <- all_files[grep("puntos.*\\.txt$", all_files, ignore.case = TRUE)]
# Regex: que termine en .pdf (el certificado)
cert_files <- all_files[grep("\\.pdf$", all_files, ignore.case = TRUE)]
```


```{r}
# 3. Procesamiento y creación del dataframe evalua_df
procesar_entrega <- function(ruta_txt) {
  # Extraer la carpeta del alumno (nivel intermedio en la ruta)
  partes <- unlist(strsplit(ruta_txt, "/"))
  carpeta_alumno <- partes[2] 
  
  # Extraer apellidos (asumiendo formato "Apellidos, Nombre_ID")
  apellidos_extraidos <- trimws(unlist(strsplit(carpeta_alumno, ","))[1])
  lineas <- readLines(ruta_txt, warn = FALSE)
  contenido_txt <- paste(lineas, collapse = " ")
  puntos_num <- as.numeric(str_extract(contenido_txt, "\\d+"))
  
  data.frame(
    apellidos = apellidos_extraidos,
    puntos = puntos_num,
    NomFile = basename(ruta_txt),
    Puntos = contenido_txt,
    stringsAsFactors = FALSE
  )
}
lista_resultados <- lapply(puntos_files, procesar_entrega)
evalua_df <- do.call(rbind, lista_resultados)

# Ordenar alfabéticamente por apellidos
evalua_df <- evalua_df[order(evalua_df$apellidos), ]


write.xlsx(evalua_df, "NotasRIntermedio.xlsx")
```


```{r}
# 4. Cruce con el listado oficial de alumnos
alumnos_mat <- read_excel("AlumnosTD25_26 (1).xlsx")
alumnos_mat$`Apellido(s)` <- trimws(alumnos_mat$`Apellido(s)`)
evalua_df$apellidos <- trimws(evalua_df$apellidos)

# Realizamos la combinación
alumnos_notas <- merge(
  alumnos_mat, 
  evalua_df, 
  by.x = "Apellido(s)",
  by.y = "apellidos", 
  all.x = TRUE           
)

# Guardar el resultado final
write.xlsx(alumnos_notas, "AlumnosNotas.xlsx")
```

